GeneticAlgorithm: main.cpp Definitions.h Utilities.h Utilities.cpp GeneticAlgorithm.h GeneticAlgorithm.cpp GeneticAlgorithmMap.h GeneticAlgorithmMap.cpp
	g++ main.cpp Definitions.h Utilities.h Utilities.cpp GeneticAlgorithm.h GeneticAlgorithm.cpp GeneticAlgorithmMap.h GeneticAlgorithmMap.cpp -o Bin/GeneticAlgorithm
